---
- hosts: localhost
  become: True
  become_user: "{{ user }}"
  roles:
    - { role: dotfiles, tags: dotfiles }
    - { role: dotfiles-gruvbox, tags: dotfiles-gruvbox }
    - { role: install-packages, tags: install-packages }
