- name: create .sources
  file:
    path: "~/.sources"
    state: directory

- name: create .zinit
  file:
    path: "~/.zinit"
    state: directory

- name: create .local/share/nvim/site/autoload/
  file:
    path: "~/.local/share/nvim/site/autoload/"
    state: directory

- name: create .tmux/plugins
  file:
    path: "~/.tmux/plugins"
    state: directory

- name: install tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: clone autojump
  git:
    repo: 'https://github.com/wting/autojump.git'
    dest: "~/.sources/autojump"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install autojump
  command: ./install.py -p ~/.local/
  args:
    chdir: ~/.sources/autojump/

- name: install zinit
  git:
    repo: 'https://github.com/zdharma/zinit.git'
    dest: "~/.zinit/bin"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "~/.sources/fzf"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install fzf
  command: ./install --bin --xdg
  args:
    chdir: ~/.sources/fzf/

- name: copy fzf* to ./local/bin
  copy:
    src: ~/.sources/fzf/bin/{{ item }}
    dest: ~/.local/bin/{{ item }}
  loop:
    - fzf
    - fzf-tmux

- name: install vim-plug to neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
    mode: '0700'

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    extra_args: --user

- name: install pynvim
  pip:
    name: pynvim
    extra_args: --user

- name: download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: "~/.sources/rustup.sh"
    mode: '0700'

- name: install rust
  command: ./rustup.sh -y
  args:
    chdir: ~/.sources/

- name: install alacritty
  command: ./cargo install alacritty
  args:
    chdir: ~/.cargo/bin/
