- name: create .sources
  file:
    path: "~/.sources"
    state: directory

- name: create .zinit
  file:
    path: "~/.zinit"
    state: directory

- name: create .local/share/nvim/site/autoload/
  file:
    path: "~/.local/share/nvim/site/autoload/"
    state: directory

- name: create .tmux/plugins
  file:
    path: "~/.tmux/plugins"
    state: directory

- name: install tpm
  git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: "~/.tmux/plugins/tpm"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: clone autojump
  git:
    repo: 'https://github.com/wting/autojump.git'
    dest: "~/.sources/autojump"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install autojump
  command: ./install.py -p ~/.local/
  args:
    chdir: ~/.sources/autojump/
  ignore_errors: true

- name: clone marker
  git:
    repo: 'https://github.com/pindexis/marker'
    dest: "~/.sources/marker"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install marker
  command: ./install.py -p ~/.local/
  args:
    chdir: ~/.sources/marker/
  ignore_errors: true

- name: install zinit
  git:
    repo: 'https://github.com/zdharma-continuum/zinit.git'
    dest: "~/.zinit/bin"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install prettier
  command: ~/.p_dotfiles/scripts/npm-wrapper-global.sh prettier

- name: install fzf
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "~/.sources/fzf"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install fzf
  command: ./install --bin --xdg
  args:
    chdir: ~/.sources/fzf/

- name: copy fzf* to ./local/bin
  copy:
    src: ~/.sources/fzf/bin/{{ item }}
    dest: ~/.local/bin/{{ item }}
  loop:
    - fzf
    - fzf-tmux

- name: clone packer
  git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    depth: 1
    dest: "~/.local/share/nvim/site/pack/packer/start/packer.nvim"
    clone: yes
    update: yes
    recursive: yes
    force: yes

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
    extra_args: --user

- name: install pynvim
  pip:
    name: pynvim
    extra_args: --user

- name: install black
  pip:
    name: black
    extra_args: --user

- name: download homebrew
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: "~/.sources/homebrew-install.sh"
    mode: '0700'

      #- name: install homebrew
      #  command: ./homebrew-install.sh < /dev/null
      #  args:
      #    chdir: ~/.sources/

- name: download rustup
  get_url:
    url: https://sh.rustup.rs
    dest: "~/.sources/rustup.sh"
    mode: '0700'

- name: install rust
  command: ./rustup.sh -y
  args:
    chdir: ~/.sources/

- name: install zellij
  command: ./cargo install zellij
  args:
    chdir: ~/.cargo/bin/
  ignore_errors: true

- name: xplr
  command: ./cargo install --locked --force xplr
  args:
    chdir: ~/.cargo/bin/
  ignore_errors: true

- name: install zoxide
  command: ./cargo install zoxide
  args:
    chdir: ~/.cargo/bin/
  ignore_errors: true

- name: install wezterm
  get_url:
    url: https://github.com/wez/wezterm/releases/download/20221119-145034-49b9839f/WezTerm-20221119-145034-49b9839f-Ubuntu18.04.AppImage
    dest: ~/bin/wezterm
    mode: '0500'
  ignore_errors: true

- name: install alacritty
  command: ./cargo install alacritty
  args:
    chdir: ~/.cargo/bin/
  ignore_errors: true

- name: install ripgrep
  command: ./cargo install ripgrep
  args:
    chdir: ~/.cargo/bin/
  ignore_errors: true

- name: download Insomnia
  get_url:
    url: https://github.com/Kong/insomnia/releases/download/core%402022.5.1/Insomnia.Core-2022.5.1.AppImage
    dest: "~/.sources/Insomnia.Core-2022.5.1.AppImage"
    mode: '0700'

- name: create link
  file:
    src: ~/.sources/Insomnia.Core-2022.5.1.AppImage
    dest: ~/bin/insomnia
    state: link
